// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.WebApi.Data;

#nullable disable

namespace Project.WebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221015153324_InitDb")]
    partial class InitDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Project.WebApi.Models.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Area")
                        .HasColumnType("float");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Long")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Population")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a381075c-8c50-4151-826f-1593b0a5cfad"),
                            Area = 100.0,
                            Code = "ABC",
                            Lat = 2.0,
                            Long = 100.0,
                            Name = "name1",
                            Population = 1000L
                        },
                        new
                        {
                            Id = new Guid("a381075c-8c50-4151-826f-1593b0a5cfae"),
                            Area = 100.0,
                            Code = "XYZ",
                            Lat = 2.0,
                            Long = 100.0,
                            Name = "name2",
                            Population = 1000L
                        },
                        new
                        {
                            Id = new Guid("a381075c-8c50-4151-826f-1593b0a5cfaf"),
                            Area = 100.0,
                            Code = "123",
                            Lat = 2.0,
                            Long = 100.0,
                            Name = "name3",
                            Population = 1000L
                        });
                });

            modelBuilder.Entity("Project.WebApi.Models.Domain.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WalkDifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.HasIndex("WalkDifficultyId");

                    b.ToTable("Walks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d381075c-8c50-4151-826f-1593b0a5cfad"),
                            Length = 10.0,
                            Name = "Marathon",
                            RegionId = new Guid("a381075c-8c50-4151-826f-1593b0a5cfad"),
                            WalkDifficultyId = new Guid("d381075c-8c50-4151-826f-1593b0a5cfad")
                        },
                        new
                        {
                            Id = new Guid("d381075c-8c50-4151-826f-1593b0a5cfae"),
                            Length = 10.0,
                            Name = "hellothon",
                            RegionId = new Guid("a381075c-8c50-4151-826f-1593b0a5cfae"),
                            WalkDifficultyId = new Guid("d381075c-8c50-4151-826f-1593b0a5cfae")
                        },
                        new
                        {
                            Id = new Guid("d381075c-8c50-4151-826f-1593b0a5cfaf"),
                            Length = 10.0,
                            Name = "hithon",
                            RegionId = new Guid("a381075c-8c50-4151-826f-1593b0a5cfaf"),
                            WalkDifficultyId = new Guid("d381075c-8c50-4151-826f-1593b0a5cfaf")
                        });
                });

            modelBuilder.Entity("Project.WebApi.Models.Domain.WalkDifficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WalkDifficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d381075c-8c50-4151-826f-1593b0a5cfad"),
                            Code = "Medium"
                        },
                        new
                        {
                            Id = new Guid("d381075c-8c50-4151-826f-1593b0a5cfae"),
                            Code = "Hard"
                        },
                        new
                        {
                            Id = new Guid("d381075c-8c50-4151-826f-1593b0a5cfaf"),
                            Code = "Easy"
                        });
                });

            modelBuilder.Entity("Project.WebApi.Models.Domain.Walk", b =>
                {
                    b.HasOne("Project.WebApi.Models.Domain.Region", "Region")
                        .WithMany("Walks")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.WebApi.Models.Domain.WalkDifficulty", "WalkDifficulty")
                        .WithMany("Walks")
                        .HasForeignKey("WalkDifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");

                    b.Navigation("WalkDifficulty");
                });

            modelBuilder.Entity("Project.WebApi.Models.Domain.Region", b =>
                {
                    b.Navigation("Walks");
                });

            modelBuilder.Entity("Project.WebApi.Models.Domain.WalkDifficulty", b =>
                {
                    b.Navigation("Walks");
                });
#pragma warning restore 612, 618
        }
    }
}
